name: The Wide Outside
favicon: null
layout_spectrum: 0.3665626391302794
typography_spectrum: 0.9438666484784335
title: The Wide Outside
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4439568486995995
  lightness: 0.18404113641008735
  saturation: 0.7394570035394281
  rhythmicContrast: 0.42493692389689386
purpose: []
